name: GitHub profile images

on:
  schedule: # 03:00 JST
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile
    steps:
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>'

      - uses: actions/checkout@v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}

      - uses: yoshi389111/github-profile-3d-contrib@7d95e7d4cdc028dd1e1cbd957d65f35efb12ae39 # 0.9.3
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          USERNAME: ${{ github.repository_owner }}

      - name: Generate stats card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true
          path: images/stats.svg
          token: ${{ steps.app-token.outputs.token }}

      - name: Commit & Push
        run: |
          ls -al profile-3d-contrib
          cp -f profile-3d-contrib/profile-season-animate.svg images/profile-3d.light.svg
          cp -f profile-3d-contrib/profile-night-rainbow.svg images/profile-3d.dark.svg
          rm -rf profile-3d-contrib

          git add -A
          git commit -m "update: profile images" || true
          git push
